# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Startbootstrap Modern Business"
license = "MIT"
licenselink = "https://github.com/juh2/hugo-startbootstrap-modern-business/blob/master/LICENSE.md"
description = "This is the Hugo version of the Start Bootstrap Theme Modern Business by Blackrock Digital LLC"
homepage = "http://siteforthistheme.com/"
tags = ["blog", "company"]
features = ["", ""]
min_version = 0.17

[author]
  name = "Jan Ulrich Hasecke"
  homepage = "http://www.hasecke.com"

# If porting an existing theme
[original]
  name = "Start Bootstrap Modern Business"
  homepage = "https://startbootstrap.com/template-overviews/modern-business/"
  repo = "https://github.com/BlackrockDigital/startbootstrap-modern-business"
